In [1]:
import numpy as np

x = np.arange(10) # 利用numpy。arange生成从0开始的10个numpy数组
y = x ** 2 # 利用广播机制，进行平方
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [2]:
np.savez("x_y-squared.npz", x_axis=x, y_axis=y) 
# np.savez(),将目标数组存为.npz，其中x_axis，y_axis存入后数组的名称，方便后去读取

In [3]:
del x, y # 删除x,y的引用

In [4]:
%whos 
# 是 IPython/Jupyter Notebook 中的一个魔法命令（Magic Command）
#用于=列出当前交互式命名空间中的所有变量，并显示它们的名称、类型、值和内存占用等详细信息。

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'E:\<...>ges\\numpy\\__init__.py'>


In [5]:
load_xy = np.load("x_y-squared.npz") # 这里np.load()仅仅能加载savez保持的文件
print(load_xy.files) # 可以推断出load_xy中files的属性显示的其中存了哪些数组，通过数组名来进行显示

['x_axis', 'y_axis']


In [6]:
%whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    NpzFile 'x_y-squared.npz'<...>with keys: x_axis, y_axis
np         module     <module 'numpy' from 'E:\<...>ges\\numpy\\__init__.py'>


In [7]:
x = load_xy["x_axis"] # 直接通过
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [12]:
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]]) 
# x[:, np.newaxis]是将一维的x变为二维的矩阵，且第一列是x，但是后续的列都是空的。
# 类似与行向量转为列向量，但是为了让其成为矩阵需要对其添加新的axis，而且还需要其他值设为空
# block是将块矩阵进行拼接，
print("the output array has shape ", array_out.shape, " with values:")
print(array_out)

the output array has shape  (10, 2)  with values:
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


In [16]:
np.savetxt("x_y-squared.csv", X=array_out, header="x, y",delimiter=",")
# 注意与np.save的区别即可，其中X=是需要输入的数组，X是不能变得，它就是待定的参数

In [19]:
del x, y

In [22]:
load_xy = np.loadtxt("x_y-squared.csv", delimiter=",")
# 注意与np.load的区别，同时还要传入该文件的分隔符

In [25]:
load_xy.shape
load_xy.dtype
# 可以看出是直接将csv文件读取为一个2dims的数组

dtype('float64')

In [24]:
x = load_xy[:, 0]
y = load_xy[:, 1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
